apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-branches-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kuna-mexa13/test-app.git
        revision: HEAD  # Resolves the latest branch (default branch)
        # filters:
        #   - branchMatch: '^dev-.*$'
        # path: .  # Path for manifests
  template:
    metadata:
      name: "{{branch}}-app"  # Application name dynamically based on branch name
    spec:
      project: aggregator
      source:
        repoURL: https://github.com/kuna-mexa13/test-app.git
        targetRevision: "{{branch}}"  # Uses current branch dynamically
        path: .  # Assumes manifests exist in the root of the branch
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{branch}}-namespace"  # Namespace dynamically created per branch
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
