apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-branches-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kuna-mexa13/test-app
        revision: "refs/heads/dev-*"  # Match all branches starting with 'dev-'
        directories:
          - path: config/apps/  # Path in each branch to generate applications
  template:
    metadata:
      name: "{{branch}}-app"  # Application name dynamically set per branch
    spec:
      project: default
      source:
        repoURL: https://github.com/kuna-mexa13/test-app
        targetRevision: "{{branch}}"  # Uses the current branch dynamically
        path: config/apps/  # Path to manifests in the branch
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{branch}}-namespace"  # Unique namespace per branch
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
