apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-branches-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kuna-mexa13/test-app
        revision: HEAD  # Use HEAD to reference the default branch
        files:
          - path: config/apps/application-*.yaml  # Dynamically match files in 'apps'
  template:
    metadata:
      name: "{{path.basename}}-app"  # Extract the basename of the file for app name
    spec:
      project: default
      source:
        repoURL: https://github.com/kuna-mexa13/test-app
        targetRevision: HEAD
        path: config/apps/  # Path within the repo
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}-namespace"  # Dynamic namespace name
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
