apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-branches-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kuna-mexa13/test-app.git
        revision: refs/heads/dev-*  # Match all branches starting with 'dev-'
        directories:
          - path: .  # Scans the repository root for manifests
  template:
    metadata:
      name: "{{branch}}-app"  # Application name based on branch name
    spec:
      project: aggregator  # Use the AppProject 'aggregator'
      source:
        repoURL: https://github.com/kuna-mexa13/test-app.git
        targetRevision: "{{branch}}"  # Dynamically uses the branch name
        path: .  # Points to the root of the repository (change if needed)
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{branch}}-namespace"  # Namespace per branch
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
