apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-feature2-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kuna-mexa13/test-app.git'
    targetRevision: HEAD
    path: app/overlays/dev-feature2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-feature2-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
