# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# # resources:
# #   - deployment.yaml
# #   - service.yaml
# #   - ingress.yaml

# resources:
#   - deployment.yaml
#   - service.yaml
#   - ingress.yaml

# patchesStrategicMerge:
#   - ingress-patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: k8s-info-ingress